
class Scrapers::NameSplitter

  RECEIVERS = [
    'Michel Pons',
    'Anabelle PRIEUR',
    'Laurent Castaings',
    'Adeline SEINE',
    'Hervé Quillet',
    'Nadia Carbonnet',
    'Adam Brunet',
    'Laurent Soria',
    'Benoit SIMORRE',
    'Laetitia Lenfant',
    'Nicolas van Velthoven',
    'Sandrine CERVI',
    'Arnaud',
    'Christelle VIGE ITASSE',
    'Virginie SAMITIER',
    'Nathalie Foulon',
    'Karine Lenfant',
    'Caroline URIOT',
    'Henri GHIRARDINI',
    'Farid BENLAZAR',
    'Stéphane LESCOMBES',
    'Corinne NAULET',
    'Anne-Laure ECHEVESTE',
    'François LAMBERT',
    'Séverine FORESTIER',
    'Lorraine MILLOT',
    'Maxime Denohme',
    'Jessica Eberlé',
    'Thierry Chapelier',
    'Audrey DARDE SENECAT',
    'Jean-Marie DUCAMIN',
    'Sylvie Vignes',
    'Audrey DALBON',
    'Sylvaine Mouton',
    'Aurélie Auvray',
    'Mathieu VILLEMONTEIL',
    'Sabine Doumergue-Reau',
    'Mme BRETON Cécile',
    'Sandrine FAVRE',
    'Nicolas SOULIER',
    'Isabelle MORELL',
    'Florent Dubois',
    'Guilaine TAVARES',
    'Eric Baur',
    'Florent DUBOIS',
    'Bénédicte HUE',
    'Audrey LAGOURGUE & Marc COUARD',
    'Etienne Guesdon-Vennerie',
    'Stéphanie Decay',
    'Stéphane Géraut',
    'Stéphanie Pellet',
    'Ducasse Bruno',
    'Laurent Bosc',
    'Laurent Mouton',
    'Amélie Delbos',
    'Chrystel DEMAEGDT',
    'Christine BLAISE',
    'Pascal MARC',
    'Lise PLESSIS',
    'Christine TOUBAS AVIGNON',
    'Francis Nogué',
    'Aline BOURGEOIS',
    'Franck Desnouhes',
    'Dominique TOCHEPORT',
    'Nathalie CAILLAULT',
    'Sophie Davet',
    'Emilie Pinel',
    'Carole VILLEFER',
    'Pascal Lassagne',
    'Catherine CANTEGREL',
    'Cécile LABARDE',
    'GUICHARNAUD Cédric / BOUCHER Allison',
    'Eric Chantry',
    'Marie ALMAYRAC',
    'Caroline GABRIEL',
    'Charlène PERAUDEAU',
    'Christine LASCORY',
    'Jean Christophe NICOLAS',
    'Catherine VANDERZEE',
    'Vincent Hausseguy',
    'Laurent Carponsin',
    'Mélanie AVIGNON',
    '',
    'Eric Mordret',
    'Diane DU CHATENET',
    'Riana RAHAROLAHY',
    'Costanzo Damien',
    'Ulrich Chofflet',
    'Catherine ROSSIGNOL-MOREAU',
    'Stéphane SANZ',
    'CLEMENT Anthony',
    'Julie RAMBEAU',
    'Emmanuel Schvan',
    'Céline FLORENT',
    'Thierry RENIER',
    'Géraldine DUMONT',
    'Jérôme Lemonnier',
    'Laurent VORGERE – Gassia KACHADOURIAN (Arcachon)',
    'Nathalie DECATOIRE',
    'Thibault Shilder / Pierre Coulomban',
    'Louis CAILHOL',
    'Olivier COURMONT',
    'Bruno DASILVA',
    'Edwige CIRIA',
    'Denis Bourbon',
    'Jean-Yves Parra',
    'Laureen BALAC',
    'Elisabeth Bernard',
    'Stéphane GROISEAU',
    'Boris RICHEBOIS',
    'Nadine et Jacques Cheminade',
    'Florence Lavarenne',
    'Pascal LE BOURCH',
    'Olivier Boulbes',
    'Sylvie LAROCHE',
    'Patrick HERRAN',
    'Stéphane Casanave-Chevrier',
    'Eric MORTIER',
    'Marielle Philip',
    'Florence Chambolle',
    'Jean Christophe Gigniac',
    'Frédéric Ruault',
    'Sandie Lacombe',
    'Cécile AMBAUD',
    'Patrick Davet',
    'Christophe REVERDY',
    'Sylvain MAZZOCCO',
    'Gwendoline MARIETTI',
    'Gwendoline MARIETTI',
    'Julie COMBES',
    'Maryse DULAS',
    'Laurence FLEURY',
    'Céline Bobacher',
    'Pierig GUENOLE',
    'Julien CRAMAIL',
    'Patrick Pujol',
    'Sébastien DUBOIS',
    'Laurent GEULIN',
    'Christian MEJAOURI',
    'Muriel FOUIX',
    'Isabelle VULLIARD',
    'Laetitia ROUMAZEILLES',
    'Sonia BARDO',
    'Jacques Chauvet',
    'Jérôme PINAUD',
    'Ludovic CASSAGNE',
    'Katia MARCHAL',
    'Franck PLOCHEL',
    'Géraldine MILON LEROY',
    'Frederick HOLMEIR',
    'Jacqueline GUESDON',
    'Florent HUSTE',
    'Karina MEYNARD',
    'Manu LE BRETON',
    'Ariane DE TERGONDE',
    'Eric Malabat',
    'Didier REVARDEL',
    'Arnaud JOCAILLE',
    'Cécile ROCHEREAU',
    'Jean-François Tastet',
    'Cécilia ROCH et Nicolas DUBOT',
    'Nathalie GIDELLE',
    'Hugo Biancheri',
    'Coussau Sally',
    'Claire ROUSSEAU',
    'Angelique vVigier Danède',
    'Hélène RAMBAUD',
    'Pierre Henri LE MOAL',
    'Frédérique CLEMENT',
    'Emilie et Rémi LEBRUNET',
    'Meryl Delpit',
    'Marjerie NAULLEAU',
    'Matthieu LECOCQ',
    'Jean-Charles Krompholtz',
    'Lucie PASCUTTO',
    'Nicolas PASCCUTTO',
    'Franck CARON',
    'Nathalie FRUGIER',
    'Sandrine RESTIER',
    'Nicolas Lebec',
    'Carine Stoll & Damien Demont',
    'Nina MUSSAUTE',
    'Laurent Cuisinaud',
    'Anne Lassurguere',
    'Delphine Nivoix',
    'Luc PASQUIER',
    'Mathieu DOAT & Anne Sophie RAGON',
    'Thierry AZCOITIA',
    'Simon ROZES & Sacha ROZES',
    'Luc METIVIER',
    'Claudine DURIF',
    'Nicolas TONON',
    'Robert RICHARD',
    'Nicolas SANS & Johan PILET',
    'Pierre JAMELIN & Johan GUYOT',
    'Edith LERAY',
    'Otis FERU',
    'Bruno BERGUIN',
    'Stephen BEUX',
    'Pierre RAPIAU',
    'Stéphane RADJI',
    'Céline Guillaume',
    'LE BOURCH Laurence',
    'Audrey Domenech & Kévin Dumaine',
    'Franck GERARD',
    'Stéphane Regnier',
    '',
    'Eric Trocellier',
    'Philippe GAUDOU',
    'Olivier DOKHAN',
    'Samuel RATURAT',
    'Gilles Massicard',
    'Stéphane Hotterbeck',
    'Sabine TEULIER',
    'Sandrine ESPOSITO',
    'Julien CAMGUILHEM',
    'Stéphan PEY',
    'Eric PELLEGRINI',
    'Stéphan COSTESEQUE',
    'Amélia Fernandez',
    'Sindy LIEBAULT',
    'Mathieu CAZALET',
    'Pierre Emmanuel BONIN',
    'Didier REVARDEL',
    'Francoise RIEUTORT',
    'Jean-Marie SOUCHAUD',
    'Erick BONNARDET',
    'Renata Machado',
    'Michel ITHURBIDE',
    'Isabelle DAVOIS',
    'Marilyn SOULIER',
    'Timo Wettlaufer',
    'Jean Francois PATIENT',
    'Thierry LESPINASSE',
    'Michel Massault',
    'Jean-François BIDEL',
    'Yoann SALCEDO',
    'Nicolas CLAMARAN-DANZELLE',
    'Jean Pierre ALVAREZ - Florian JENDRASIAK',
    'Virginie COURTIOUX',
    'Yann CRABE',
    'Hélène CORNIL',
    'Zahra HACHT',
    'Carine HOQUET'
  ]

  attr_reader :first_name, :last_name

  def initialize(name)

    last_name = find_upper_name(name)

    name = delete_useless_text(name) # on efface le texte inutile (situé après les séparateurs tels que & – ( / - et)

    if last_name != nil
      name = name.sub(last_name, "") # si le nom de famille a été trouvé, on le supprime du texte
      first_name = name.strip
    elsif
      i = name.index(" ")
      first_name = name[0..i-1]
      last_name = name[i+1..name.length-1]
    end

    @last_name = last_name
    @first_name = first_name
  end

  def self.test
    RECEIVERS.each { |n|
      splitter = self.new(n)
      puts "** #{splitter.first_name} --- #{splitter.last_name} **"
    }
  end

  private

  def delete_useless_text(name)
    i = name.index(/\s*([&–\(\/)]| et | -)/)
    return (i != nil) ? name.slice(0..i-1) : name
  end

  def find_upper_name(name)
    s = name.slice(/[- A-Z]*[A-Z]{2,}/)
    return (s != nil) ? s.strip : nil
  end

end